# Generated by Django 4.0.5 on 2022-07-04 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('marca', models.CharField(max_length=30)),
                ('costo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tipo_pantalla', models.CharField(max_length=20)),
                ('tamano_pantalla', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
